[phases.setup]
nixPkgs = ['nodejs']

[phases.install] 
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.12.0 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmd = "pnpm run build"

[start]
cmd = "pnpm run start"
