[project]
root = "da-submission-manager"

[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.12.0 --activate", 
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmd = "pnpm --filter @dasub/api build"

[start]
cmd = "pnpm --filter @dasub/api start"

